.TH IOSOCKS 8 "Feb 25, 2015"
.SH NAME
iosocks \- A lightweight tunnel proxy

.SH SYNOPSIS
\fBioserver\fR|\fBioclient\fR|\fBioredir\fR
    \-h, \-\-help
    \-c, \-\-config <file>   config file
    \-d, \-\-daemon          daemonize after initialization
    \-p, \-\-pidfile <file>  PID file
    \-\-logfile <file>      log file

.SH DESCRIPTION
\fBiosocks\fR is a lightweight tunnel proxy, provides a SOCKS5 proxy and a transparent  TCP  proxy.
.PP
\fBiosocks\fR consists of 3 components. \fBioserver\fR runs on a remote server to provide secured tunnel service. \fBioclient\fR is a standard SOCKS5 proxy that trasmits all data to \fBioserver\fR. \fBioredir\fR is a transparent TCP proxy and requires netfilter's NAT function.
.PP

.SH OPTIONS
.TP
.B \-h, \-\-help
Print a help message and exit.
.TP
.B \-c, \-\-config \fI<file>\fR
Config file.
.TP
.B \-d, \-\-daemon
Daemonize after initialization.
.TP
.B \-p, \-\-pidfile \fI<file>\fR
PID file.
.TP
.B \-\-logfile \fI<file>\fR
Log file.

.SH CONFIG FILE
The syntax of the config file is inspired by Microsoft Windows \fI.ini\fP files.

.SS GLOBAL
.TP
[global] section defines common settings.
.TP
\fIuser=\fR
.br
Set to specified user after bind, default: nobody
.TP
\fIgroup=\fR
.br
Set to specified group after bind

.SS SERVER
.TP
[server] section defines a remote server. This section can appear more than once.
.TP
\fIaddress=\fR
.br
Server address, default: 0.0.0.0
.TP
\fIport=\fR
.br
Server port, default: 1205
.TP
\fIkey=\fR
.br
Encryption key

.SS LOCAL
[local] section defines a local client.
.TP
.B \fIaddress=\fR
Local address, default: 127.0.0.1
.br
.TP
.B \fIport=\fR
.br
Local port, default: 1080

.SS REDIR
[redir] section define a transparent TCP proxy
.TP
.B \fIaddress=\fR
Local address, default: 127.0.0.1
.br
.TP
.B \fIport=\fR
.br
Local port, default: 1081

.SH EXAMPLE
Here is a sample config file:

    [global]
    user=nobody
    group=nobody

    [server]
    address=192.168.1.1
    port=1205, 80, 443
    key=testkey

    [server]
    address=192.168.1.2
    port=1205, 80, 443
    key=testkey2

    [local]
    address=127.0.0.1
    port=1080

    [redir]
    address=127.0.0.1
    port=1081

.SH AUTHOR
.PP
This manual page was written by Xiaoxiao Pu <i@xiaoxiao.im>.
