.TH IOSOCKS 8 "Jan 6, 2015"
.SH NAME
iosocks \- A lightweight SOCKS5 proxy

.ds Is  \fBisocks\fR
.ds Os  \fBosocks\fR
.ds Ns  \fBiodns\fR
.ds Me  \fBiosocks\fR

.SH SYNOPSIS
\*(Is|\*(Os|\*(Ns
    \-h, \-\-help
    \-c <config_file>

.SH DESCRIPTION
\*(Me is a lightweight SOCKS5 proxy written in pure C, using \fBlibev\fR as event loop library. It has high performance and low resource consumption.
.PP
\*(Me consists of three components. \*(Os runs on a remote server to provide secured tunnel service. \*(Is is a standard SOCKS5 proxy that trasmits all data to \*(Os. \*(Ns is a DNS forwarder that transmits all DNS queries to \*(Os.
.PP

.SH OPTIONS
.TP
.B \-c \fI<config_file>\fR
Config file.
.TP
.B \-h, \-\-help
Print a help message and exit.

.SH CONFIG FILE
The syntax of the config file is inspired by Microsoft Windows \fI.ini\fP files.
.SS SERVER
.TP
[server] section defines a remote server. This section can appear more than once.
.TP
\fIaddress=\fR
.br
Server address, default: 0.0.0.0
.TP
\fIport=\fR
.br
Server port, default: 1205
.TP
\fIkey=\fR
.br
Encryption key

.SS LOCAL
[local] section defines a local client.
.TP
.B \fIaddress=\fR
Local address, default: 127.0.0.1
.br
.TP
.B \fIport=\fR
.br
Local port, default: 1080

.SS DNS
[dns] section defines a DNS server.
.TP
.B \fIaddress=\fR
DNS listen address, default: 127.0.0.1
.br
.TP
.B \fIport=\fR
.br
DNS listen port, default: 5300
.TP
.B \fIupstream_addr=\fR
Upstream DNS server address, default: 8.8.8.8
.br
.TP
.B \fIupstream_port=\fR
.br
Upstream DNS server port, default: 53


.SH EXAMPLE
Here is a sample config file:

    [server]
    address=192.168.1.1
    port=1205
    key=testkey
    [server]
    address=192.168.1.2
    port=1205
    key=testkey2
    [local]
    address=127.0.0.1
    port=1080
    [dns]
    address=127.0.0.1
    port=5300
    upstream_addr=8.8.8.8
    upstream_port=53

.SH AUTHOR
.PP
This manual page was written by Xiaoxiao Pu <i@xiaoxiao.im>.
